"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  LineChart,
  Line,
  PieChart,
  Pie,
  Cell,
  Legend,
} from "recharts";
import {
  ArrowLeft,
  Download,
  Search,
  Brain,
  Link2,
  Radio,
  FileText,
  ChevronDown,
  ChevronUp,
  Sparkles,
} from "lucide-react";
import { useSharedWorkspace } from "../../../src/context/SharedWorkspaceContext";

const CHART_TEAL = "#00E5CC";
const CHART_VIOLET = "#8B5CF6";
const CHART_AMBER = "#F59E0B";
const CHART_SLATE = "rgba(148, 163, 184, 0.65)";
const CHART_MUTED = "rgba(255,255,255,0.25)";
const CHART_PALETTE = [CHART_TEAL, CHART_VIOLET, CHART_AMBER, CHART_SLATE, CHART_MUTED];

const FALLBACK_MARKET_SHARE = [
  { name: "Competitor A", share: 32, fill: CHART_TEAL },
  { name: "Competitor B", share: 28, fill: CHART_VIOLET },
  { name: "Competitor C", share: 18, fill: CHART_AMBER },
  { name: "Others", share: 22, fill: CHART_MUTED },
];
const FALLBACK_OPPORTUNITY_GAP = [
  { segment: "4,000m depth", gap: 78, demand: 92 },
  { segment: "Survey drones", gap: 65, demand: 88 },
  { segment: "Maintenance ROV", gap: 72, demand: 85 },
  { segment: "Data pipelines", gap: 58, demand: 80 },
  { segment: "Fleet mgmt", gap: 45, demand: 70 },
];
const FALLBACK_TREND = [
  { month: "Jan", market: 62, competitors: 58 },
  { month: "Feb", market: 65, competitors: 60 },
  { month: "Mar", market: 68, competitors: 62 },
  { month: "Apr", market: 72, competitors: 65 },
  { month: "May", market: 78, competitors: 68 },
  { month: "Jun", market: 82, competitors: 70 },
];
const FALLBACK_PIE_COLORS = CHART_PALETTE;
const FALLBACK_SUMMARY =
  "Our AI analyst has scanned current market data and identified a clear gap in 4,000m depth drone capabilities. Incumbent players (Competitor A at 32% share, Competitor B at 28%) under-serve the survey and maintenance ROV segments. Your opportunity score in the depth segment is 78/100, with demand at 92—indicating strong whitespace. We recommend positioning in this niche before incumbents expand, and using data pipeline differentiation as a secondary wedge.";
const FALLBACK_REPORT =
  "Market Intelligence Report – Generated by Nova 2 Lite\n\nExecutive Summary:\nOur analysis identifies a clear gap in 4,000m depth drone capabilities. Competitor A leads with 32% share but under-serves the survey and maintenance segments. Your opportunity score in depth drones is 78/100 with demand at 92.\n\nRecommendations:\n• Position in the 4,000m depth niche before incumbents expand.\n• Emphasize data pipeline differentiation (gap 58, demand 80).\n• Consider fleet management as a secondary wedge (gap 45).\n\n[Full mock report – replace with real PDF/API in production.]";

const CHART_CARD_CLASS =
  "rounded-2xl border border-white/10 bg-white/[0.06] backdrop-blur-xl p-5 md:p-6 shadow-[0_4px_24px_rgba(0,0,0,0.25),0_0_1px_rgba(255,255,255,0.08)]";
const TOOLTIP_STYLE = {
  contentStyle: {
    background: "rgba(15, 23, 42, 0.96)",
    border: "1px solid rgba(148, 163, 184, 0.2)",
    borderRadius: 10,
    padding: "10px 14px",
    boxShadow: "0 10px 40px rgba(0,0,0,0.4)",
  },
  labelStyle: { color: "rgba(226, 232, 240, 0.95)", fontWeight: 600, marginBottom: 4, fontSize: 12 },
  itemStyle: { color: "rgba(203, 213, 225, 0.9)", fontSize: 12 },
};

const containerVariants = {
  hidden: { opacity: 0 },
  visible: (i = 0) => ({
    opacity: 1,
    transition: { staggerChildren: 0.04, delayChildren: i * 0.1 },
  }),
  exit: { opacity: 0 },
};
const itemVariants = {
  hidden: { opacity: 0, y: 8 },
  visible: { opacity: 1, y: 0 },
};

export default function MarketIntelligencePage() {
  const {
    sharedWorkspace,
    loading,
    refreshFromBackend,
    triggerMarketIntel,
    triggerMarketIntelFollowUp,
    clearMarketIntelFollowUps,
    marketIntelStreamPhase,
    marketIntelStreamedText,
    marketIntelResearchSteps,
  } = useSharedWorkspace();
  const mi = sharedWorkspace?.market_intel;
  const [hasTriggeredReport, setHasTriggeredReport] = useState(false);
  const [followUpInput, setFollowUpInput] = useState("");
  const [followUpSubmitting, setFollowUpSubmitting] = useState(false);
  const [showSourcesList, setShowSourcesList] = useState(false);
  const [showResearchLog, setShowResearchLog] = useState(false);
  const chart1Ref = useRef<HTMLElement>(null);
  const chart2Ref = useRef<HTMLElement>(null);
  const chart3Ref = useRef<HTMLElement>(null);
  const chart4Ref = useRef<HTMLElement>(null);
  const streamEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    refreshFromBackend();
  }, [refreshFromBackend]);

  useEffect(() => {
    return () => {
      void clearMarketIntelFollowUps();
    };
  }, [clearMarketIntelFollowUps]);

  useEffect(() => {
    if (marketIntelStreamedText) streamEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [marketIntelStreamedText]);

  const isStreaming =
    hasTriggeredReport &&
    (loading || marketIntelStreamPhase !== "idle" || marketIntelStreamedText.length > 0);
  const showContent = hasTriggeredReport && mi?.status === "COMPLETE" && !isStreaming;

  const summary = showContent ? (mi?.summary ?? FALLBACK_SUMMARY) : "";
  const reportText = showContent ? (mi?.report_text ?? FALLBACK_REPORT) : "";
  const marketShareData = (showContent && mi?.market_share_data?.length
    ? mi.market_share_data
    : FALLBACK_MARKET_SHARE) as { name: string; share: number; fill: string }[];
  const opportunityGapData = (showContent && mi?.opportunity_gap_data?.length
    ? mi.opportunity_gap_data
    : FALLBACK_OPPORTUNITY_GAP) as { segment: string; gap: number; demand: number }[];
  const trendData = (showContent && mi?.trend_data?.length ? mi.trend_data : FALLBACK_TREND) as {
    month: string;
    market: number;
    competitors: number;
  }[];
  const pieColors = (showContent && mi?.pie_colors?.length ? mi.pie_colors : FALLBACK_PIE_COLORS) as string[];

  const handleGenerateReport = () => {
    setHasTriggeredReport(true);
    triggerMarketIntel();
  };

  const handleFollowUpSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const q = followUpInput.trim();
    if (!q || followUpSubmitting) return;
    setFollowUpSubmitting(true);
    try {
      await triggerMarketIntelFollowUp(q);
      setFollowUpInput("");
    } finally {
      setFollowUpSubmitting(false);
    }
  };

  const handleDownloadReport = async () => {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ format: "a4" });
    const margin = 20;
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const textWidth = pageWidth - 2 * margin;
    let y = margin;
    const lineHeight = 5.5;
    const sectionGap = 4;

    const addPageIfNeeded = (need: number) => {
      if (y + need > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }
    };

    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("Market Intelligence Report", margin, y);
    y += 10;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    y += sectionGap;

    const reportParagraphs = reportText
      .split(/\n\n+/)
      .map((p) => p.trim())
      .filter(Boolean);
    for (const block of reportParagraphs) {
      addPageIfNeeded(lineHeight * 3);
      const isHeader = /^#+\s/.test(block) || /^\*\*[^*]+\*\*/.test(block);
      if (isHeader) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
      }
      const cleanBlock = block.replace(/^#+\s*/, "").replace(/\*\*/g, "");
      const lines = doc.splitTextToSize(cleanBlock, textWidth);
      for (const line of lines) {
        addPageIfNeeded(lineHeight);
        doc.text(line, margin, y);
        y += lineHeight;
      }
      if (isHeader) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        y += 2;
      }
      y += sectionGap;
    }

    const chartRefs = [chart1Ref, chart2Ref, chart3Ref, chart4Ref];
    try {
      const html2canvas = (await import("html2canvas")).default;
      const chartImgWidth = pageWidth - 2 * margin;
      const chartImgHeight = 70;
      for (const ref of chartRefs) {
        const el = ref.current;
        if (!el) continue;
        addPageIfNeeded(chartImgHeight + 15);
        const canvas = await html2canvas(el, {
          scale: 2,
          useCORS: true,
          backgroundColor: "#1e293b",
          logging: false,
        });
        const imgData = canvas.toDataURL("image/png");
        doc.addImage(imgData, "PNG", margin, y, chartImgWidth, chartImgHeight);
        y += chartImgHeight + 8;
      }
    } catch {
      /* skip charts */
    }

    const sources =
      showContent && Array.isArray(mi?.sources) && mi.sources.length > 0 ? mi.sources : [];
    if (sources.length > 0) {
      addPageIfNeeded(20);
      y += 6;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text("Sources", margin, y);
      y += lineHeight + 2;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      for (const s of sources) {
        const url = (s as { url?: string })?.url;
        const title =
          (s as { title?: string })?.title ??
          (s as { domain?: string })?.domain ??
          url ??
          "Source";
        addPageIfNeeded(lineHeight + 2);
        const linkText =
          typeof url === "string" && url.startsWith("http") ? title : `${title}: ${url ?? ""}`;
        const linkTextShort = linkText.length > 80 ? linkText.slice(0, 77) + "…" : linkText;
        if (typeof url === "string" && url.startsWith("http")) {
          doc.textWithLink(linkTextShort, margin, y, { url });
        } else {
          doc.text(linkTextShort, margin, y);
        }
        y += lineHeight + 2;
      }
    }
    doc.save("market-intelligence-report.pdf");
  };

  return (
    <main className="relative min-h-screen px-4 sm:px-6 py-8 sm:py-10 flex flex-col gap-8 pb-16 overflow-hidden">
      {/* Video background */}
      <div className="fixed inset-0 z-0">
        <video
          autoPlay
          muted
          loop
          playsInline
          className="absolute inset-0 w-full h-full object-cover"
          aria-hidden
        >
          <source src="/videos/seapic.mp4" type="video/mp4" />
        </video>
        <div
          className="absolute inset-0 bg-gradient-to-b from-black/60 via-midnightTrench/75 to-black/80"
          aria-hidden
        />
      </div>

      {/* Header */}
      <header className="relative z-10 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <Link
          href="/mission-control"
          className="inline-flex items-center gap-2 text-sm text-white/80 hover:text-biolumeTeal transition w-fit"
        >
          <ArrowLeft className="h-4 w-4 shrink-0" />
          Back to Mission Control
        </Link>
        {showContent && (
          <h1 className="text-xl sm:text-2xl md:text-3xl font-semibold tracking-tight text-white drop-shadow-sm">
            Competitor & Market Analysis
          </h1>
        )}
      </header>

      {/* ——— Streaming: phase stepper + research / synthesize panels ——— */}
      <AnimatePresence mode="wait">
        {!showContent && isStreaming && (
          <motion.section
            key="streaming"
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="relative z-10 max-w-4xl mx-auto w-full space-y-6"
          >
            {/* Phase stepper */}
            <div className="flex items-center justify-center gap-2 sm:gap-4">
              <div className="flex items-center gap-2">
                <div
                  className={`flex items-center justify-center w-9 h-9 rounded-full border-2 transition-all ${
                    marketIntelStreamPhase === "researching"
                      ? "border-biolumeTeal bg-biolumeTeal/20 text-biolumeTeal shadow-[0_0_20px_rgba(0,255,229,0.3)]"
                      : marketIntelStreamPhase === "synthesizing" || marketIntelStreamPhase === "idle"
                        ? "border-biolumeTeal/60 bg-biolumeTeal/10 text-biolumeTeal"
                        : "border-white/20 bg-white/5 text-white/60"
                  }`}
                >
                  {marketIntelStreamPhase === "synthesizing" || marketIntelStreamPhase === "idle" ? (
                    <span className="text-sm font-bold">✓</span>
                  ) : (
                    <Radio className="h-4 w-4" />
                  )}
                </div>
                <span className="text-sm font-medium text-white/90 hidden sm:inline">Research</span>
              </div>
              <div className="w-8 sm:w-12 h-0.5 bg-white/20 rounded-full overflow-hidden">
                <motion.div
                  className="h-full bg-biolumeTeal rounded-full"
                  initial={{ width: "0%" }}
                  animate={{
                    width:
                      marketIntelStreamPhase === "synthesizing" || marketIntelStreamPhase === "idle"
                        ? "100%"
                        : "50%",
                  }}
                  transition={{ duration: 0.4 }}
                />
              </div>
              <div className="flex items-center gap-2">
                <div
                  className={`flex items-center justify-center w-9 h-9 rounded-full border-2 transition-all ${
                    marketIntelStreamPhase === "synthesizing"
                      ? "border-electricJellyfish bg-electricJellyfish/20 text-electricJellyfish shadow-[0_0_20px_rgba(117,35,255,0.3)]"
                      : marketIntelStreamPhase === "idle"
                        ? "border-electricJellyfish/60 bg-electricJellyfish/10 text-electricJellyfish"
                        : "border-white/20 bg-white/5 text-white/50"
                  }`}
                >
                  {marketIntelStreamPhase === "idle" ? (
                    <span className="text-sm font-bold">✓</span>
                  ) : (
                    <FileText className="h-4 w-4" />
                  )}
                </div>
                <span className="text-sm font-medium text-white/90 hidden sm:inline">Report</span>
              </div>
            </div>

            {/* Main streaming card */}
            <div className="relative rounded-2xl border border-white/10 bg-black/40 backdrop-blur-xl overflow-hidden shadow-[0_8px_32px_rgba(0,0,0,0.4)]">
              {/* Scan line (research phase) */}
              {marketIntelStreamPhase === "researching" && (
                <div
                  className="absolute inset-0 pointer-events-none z-[1] overflow-hidden rounded-2xl"
                  aria-hidden
                >
                  <div
                    className="absolute left-0 right-0 h-px bg-gradient-to-r from-transparent via-biolumeTeal/50 to-transparent animate-[intel-scan_3s_ease-in-out_infinite]"
                    style={{ top: 0 }}
                  />
                </div>
              )}

              <div className="relative z-10 p-5 sm:p-6">
                {/* Research phase */}
                {marketIntelStreamPhase === "researching" && (
                  <div className="space-y-4">
                    <div className="flex items-center gap-3">
                      <div className="flex items-center justify-center w-10 h-10 rounded-xl bg-biolumeTeal/15 border border-biolumeTeal/30">
                        <Search className="h-5 w-5 text-biolumeTeal" />
                      </div>
                      <div>
                        <h2 className="text-lg font-semibold text-white">Scanning the web</h2>
                        <p className="text-xs text-white/60">
                          Running 4–6 searches for market size, competitors, trends & gaps. Usually 30–90s.
                        </p>
                      </div>
                    </div>
                    {marketIntelResearchSteps.length > 0 && (
                      <motion.div
                        variants={containerVariants}
                        initial="hidden"
                        animate="visible"
                        className="max-h-[320px] overflow-y-auto pr-1 scrollbar-thin"
                      >
                        <div className="relative pl-3">
                          <div className="absolute top-1 bottom-1 left-1 w-px bg-gradient-to-b from-biolumeTeal/40 via-white/10 to-electricJellyfish/40 pointer-events-none" />
                          <ul className="space-y-2">
                            {marketIntelResearchSteps.map((step, i) => {
                              const indexLabel = i + 1;
                              const isSearch = step.type === "search";
                              const isCitation = step.type === "citation";
                              const isReasoning = step.type === "reasoning";
                              return (
                                <motion.li
                                  key={i}
                                  variants={itemVariants}
                                  className="relative flex gap-3 items-start"
                                >
                                  <div className="mt-1 flex flex-col items-center gap-1">
                                    <div
                                      className={`flex items-center justify-center w-6 h-6 rounded-full border text-[0.65rem] font-semibold ${
                                        isSearch
                                          ? "border-amber-300/70 bg-amber-400/20 text-amber-100"
                                          : isCitation
                                            ? "border-emerald-300/70 bg-emerald-400/20 text-emerald-100"
                                            : "border-biolumeTeal/60 bg-biolumeTeal/20 text-biolumeTeal"
                                      }`}
                                    >
                                      {indexLabel}
                                    </div>
                                  </div>
                                  <div className="flex-1 rounded-xl bg-white/[0.04] border border-white/5 px-3 py-2.5">
                                    <div className="flex items-center gap-2 mb-1.5">
                                      {isReasoning && (
                                        <>
                                          <Brain className="h-3.5 w-3.5 text-biolumeTeal/80" />
                                          <span className="text-[0.7rem] font-semibold uppercase tracking-[0.14em] text-biolumeTeal/80">
                                            Thinking
                                          </span>
                                        </>
                                      )}
                                      {isSearch && (
                                        <>
                                          <Search className="h-3.5 w-3.5 text-amber-300/90" />
                                          <span className="text-[0.7rem] font-semibold uppercase tracking-[0.14em] text-amber-200/90">
                                            Web query
                                          </span>
                                        </>
                                      )}
                                      {isCitation && (
                                        <>
                                          <Link2 className="h-3.5 w-3.5 text-emerald-300/90" />
                                          <span className="text-[0.7rem] font-semibold uppercase tracking-[0.14em] text-emerald-200/90">
                                            Source
                                          </span>
                                        </>
                                      )}
                                    </div>
                                    {isReasoning && (
                                      <p className="text-xs sm:text-sm text-white/75 leading-relaxed">
                                        {step.text ?? ""}
                                      </p>
                                    )}
                                    {isSearch && (
                                      <p className="text-xs sm:text-sm text-white/90 leading-relaxed">
                                        {step.text ?? "Searching…"}
                                      </p>
                                    )}
                                    {isCitation && (
                                      <p className="text-xs sm:text-sm leading-relaxed">
                                        {step.url ? (
                                          <a
                                            href={step.url}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="text-biolumeTeal/95 hover:underline break-all"
                                          >
                                            {step.text ?? step.url}
                                          </a>
                                        ) : (
                                          <span className="text-white/75">{step.text ?? "Source"}</span>
                                        )}
                                      </p>
                                    )}
                                  </div>
                                </motion.li>
                              );
                            })}
                          </ul>
                        </div>
                      </motion.div>
                    )}
                    {marketIntelResearchSteps.length === 0 && (
                      <div className="flex items-center gap-2 text-white/50 text-sm py-4">
                        <motion.span
                          animate={{ opacity: [0.4, 1, 0.4] }}
                          transition={{ duration: 1.5, repeat: Infinity }}
                        >
                          Connecting to search…
                        </motion.span>
                      </div>
                    )}
                  </div>
                )}

                {/* Synthesize phase */}
                {marketIntelStreamPhase === "synthesizing" && (
                  <div className="space-y-4">
                    <div className="flex items-center gap-3">
                      <div className="flex items-center justify-center w-10 h-10 rounded-xl bg-electricJellyfish/15 border border-electricJellyfish/30">
                        <FileText className="h-5 w-5 text-electricJellyfish" />
                      </div>
                      <div>
                        <h2 className="text-lg font-semibold text-white">Writing your report</h2>
                        <p className="text-xs text-white/60">
                          Synthesizing research into your market intelligence brief.
                        </p>
                      </div>
                    </div>
                    {marketIntelResearchSteps.length > 0 && (
                      <div className="rounded-xl border border-white/10 bg-white/[0.03] overflow-hidden">
                        <button
                          type="button"
                          onClick={() => setShowResearchLog((v) => !v)}
                          className="w-full flex items-center justify-between px-3 py-2.5 text-left text-xs font-medium text-white/70 hover:text-white/90 hover:bg-white/5 transition"
                        >
                          <span>Research log — {marketIntelResearchSteps.length} steps</span>
                          {showResearchLog ? (
                            <ChevronUp className="h-4 w-4" />
                          ) : (
                            <ChevronDown className="h-4 w-4" />
                          )}
                        </button>
                        {showResearchLog && (
                          <ul className="max-h-[180px] overflow-y-auto border-t border-white/10 divide-y divide-white/5 p-2">
                            {marketIntelResearchSteps.map((step, i) => (
                              <li key={i} className="py-1.5 px-2 flex gap-2 items-start text-xs">
                                {step.type === "search" && (
                                  <>
                                    <Search className="h-3.5 w-3.5 shrink-0 mt-0.5 text-amber-400/80" />
                                    <span className="text-white/70">Search: {step.text ?? "…"}</span>
                                  </>
                                )}
                                {step.type === "citation" && (
                                  <>
                                    <Link2 className="h-3.5 w-3.5 shrink-0 mt-0.5 text-emerald-400/80" />
                                    {step.url ? (
                                      <a
                                        href={step.url}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="text-biolumeTeal/90 hover:underline break-all"
                                      >
                                        {step.text ?? step.url}
                                      </a>
                                    ) : (
                                      <span className="text-white/60">{step.text ?? "Source"}</span>
                                    )}
                                  </>
                                )}
                                {step.type === "reasoning" && (
                                  <>
                                    <Brain className="h-3.5 w-3.5 shrink-0 mt-0.5 text-biolumeTeal/70" />
                                    <span className="text-white/60 italic">{step.text ?? ""}</span>
                                  </>
                                )}
                              </li>
                            ))}
                          </ul>
                        )}
                      </div>
                    )}
                    <div className="rounded-xl border border-white/10 bg-black/30 p-4 min-h-[160px]">
                      <p className="text-sm md:text-base text-white/90 leading-relaxed whitespace-pre-wrap font-[inherit]">
                        {marketIntelStreamedText || "\u00a0"}
                      </p>
                      <div ref={streamEndRef} className="inline-block w-2 h-4 ml-0.5 bg-biolumeTeal/80 rounded-sm animate-[typing-cursor_1s_step-end_infinite]" />
                    </div>
                  </div>
                )}

                {marketIntelStreamPhase === "idle" && loading && !marketIntelStreamedText && (
                  <p className="text-white/80 text-sm py-4">Starting deep research…</p>
                )}
              </div>
            </div>
          </motion.section>
        )}
      </AnimatePresence>

      {/* ——— Start state: no report, not streaming ——— */}
      {!showContent && !isStreaming && (
        <motion.section
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="relative z-10 flex flex-col items-center justify-center min-h-[55vh] px-4"
        >
          <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
            <div
              className="w-[280px] h-[280px] sm:w-[320px] sm:h-[320px] rounded-full border border-white/5"
              style={{
                background: "radial-gradient(circle, rgba(0,255,229,0.06) 0%, transparent 70%)",
              }}
            />
            <div className="absolute w-[200px] h-[200px] sm:w-[240px] sm:h-[240px] rounded-full border border-white/[0.07] bg-transparent" />
          </div>
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="relative z-10 text-center max-w-lg"
          >
            <div className="inline-flex items-center gap-2 rounded-full border border-biolumeTeal/30 bg-biolumeTeal/10 px-3 py-1 text-xs font-medium text-biolumeTeal/90 mb-6">
              <Sparkles className="h-3.5 w-3.5" />
              Web-grounded analysis
            </div>
            <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white tracking-tight mb-3">
              Market Intelligence
            </h2>
            <p className="text-white/70 text-sm sm:text-base mb-8 leading-relaxed">
              Run a web-backed market scan, then get a full report with gaps, competitors, and
              recommendations—streamed as it&apos;s written.
            </p>
            <motion.button
              onClick={handleGenerateReport}
              disabled={loading}
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              className="inline-flex items-center gap-2.5 px-8 py-3.5 rounded-2xl border-2 border-biolumeTeal/50 bg-biolumeTeal/15 text-biolumeTeal text-base font-semibold hover:bg-biolumeTeal/25 hover:border-biolumeTeal/70 hover:shadow-[0_0_30px_rgba(0,255,229,0.2)] disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100 transition-all"
            >
              <Radio className="h-5 w-5" />
              Generate report
            </motion.button>
            <p className="mt-4 text-white/40 text-xs">Phase 1: Web research · Phase 2: Report</p>
          </motion.div>
        </motion.section>
      )}

      {/* ——— Report view: summary, sources, follow-up, charts ——— */}
      {showContent && (
        <>
          {/* Executive summary hero */}
          <motion.section
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.35 }}
            className="relative z-10 max-w-4xl mx-auto w-full"
          >
            <div className="rounded-2xl border border-biolumeTeal/20 bg-gradient-to-br from-biolumeTeal/10 to-electricJellyfish/5 backdrop-blur-xl p-6 sm:p-8 shadow-[0_8px_32px_rgba(0,0,0,0.3)]">
              <div className="inline-flex items-center gap-2 rounded-lg bg-biolumeTeal/15 border border-biolumeTeal/30 px-2.5 py-1 text-xs font-semibold text-biolumeTeal mb-4">
                <FileText className="h-3.5 w-3.5" />
                Executive summary
              </div>
              <p className="text-sm sm:text-base text-white/92 leading-relaxed whitespace-pre-line">
                {summary}
              </p>
              {/* Sources toggle */}
              {showContent && Array.isArray(mi?.sources) && mi.sources.length > 0 && (
                <div className="mt-5 pt-4 border-t border-white/15">
                  <button
                    type="button"
                    onClick={() => setShowSourcesList((v) => !v)}
                    className="inline-flex items-center gap-2 text-sm font-medium text-biolumeTeal hover:text-biolumeTeal/80 focus:outline-none focus:ring-2 focus:ring-biolumeTeal/40 rounded-lg px-2 py-1 transition"
                  >
                    <Link2 className="h-4 w-4 shrink-0" />
                    {showSourcesList ? "Hide web sources" : `View web sources (${mi.sources.length})`}
                  </button>
                  <AnimatePresence>
                    {showSourcesList && (
                      <motion.ul
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.2 }}
                        className="flex flex-col gap-2 mt-3 overflow-hidden"
                      >
                        {mi.sources.map((s, i) => {
                          const url = s?.url ?? undefined;
                          const title =
                            (s?.title ?? s?.domain ?? url ?? `Source ${i + 1}`) ?? "";
                          const href =
                            typeof url === "string" && url.startsWith("http") ? url : undefined;
                          return (
                            <li key={i} className="text-sm pl-1">
                              {href ? (
                                <a
                                  href={href}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  className="text-biolumeTeal/95 hover:underline break-all text-xs"
                                >
                                  {title}
                                </a>
                              ) : (
                                <span className="text-white/70 text-xs">{title}</span>
                              )}
                            </li>
                          );
                        })}
                      </motion.ul>
                    )}
                  </AnimatePresence>
                </div>
              )}
              {/* Follow-up Q&A */}
              <div className="mt-5 pt-4 border-t border-white/15">
                <h3 className="text-sm font-semibold text-white/95 mb-1">Ask a follow-up</h3>
                <p className="text-xs text-white/55 mb-3">
                  Ask about the report (e.g. regulatory risk, competitors). Nova answers using the
                  report context.
                </p>
                <form onSubmit={handleFollowUpSubmit} className="flex flex-col sm:flex-row gap-2">
                  <input
                    type="text"
                    value={followUpInput}
                    onChange={(e) => setFollowUpInput(e.target.value)}
                    placeholder="e.g. What about regulatory risk in the EU?"
                    className="flex-1 min-w-0 px-4 py-2.5 rounded-xl border border-white/20 bg-white/5 text-white placeholder-white/40 text-sm focus:outline-none focus:ring-2 focus:ring-biolumeTeal/50 focus:border-biolumeTeal/40 transition"
                    disabled={followUpSubmitting || loading}
                  />
                  <button
                    type="submit"
                    disabled={!followUpInput.trim() || followUpSubmitting || loading}
                    className="px-5 py-2.5 rounded-xl border border-biolumeTeal/50 bg-biolumeTeal/20 text-biolumeTeal text-sm font-medium hover:bg-biolumeTeal/30 disabled:opacity-50 disabled:cursor-not-allowed transition shrink-0"
                  >
                    {followUpSubmitting ? "Asking…" : "Ask"}
                  </button>
                </form>
                {Array.isArray(mi?.follow_up_answers) && mi.follow_up_answers.length > 0 && (
                  <ul className="mt-4 space-y-3">
                    {mi.follow_up_answers.map((qa, i) => (
                      <li
                        key={i}
                        className="rounded-xl border border-white/10 bg-white/[0.04] p-4 backdrop-blur-sm"
                      >
                        <p className="text-xs font-semibold text-biolumeTeal/95 mb-1.5">
                          Q: {(qa as { question?: string }).question}
                        </p>
                        <p className="text-sm text-white/88 whitespace-pre-wrap leading-relaxed">
                          {(qa as { answer?: string }).answer}
                        </p>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
              {/* Actions */}
              <div className="mt-5 pt-4 border-t border-white/15 flex flex-wrap items-center gap-3">
                <button
                  onClick={handleGenerateReport}
                  disabled={loading || mi?.status === "SYNCING"}
                  className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border border-white/25 bg-white/10 text-white text-sm font-medium hover:bg-white/15 disabled:opacity-50 disabled:cursor-not-allowed transition"
                >
                  {mi?.status === "SYNCING" ? "Generating…" : "Generate again"}
                </button>
                <button
                  onClick={handleDownloadReport}
                  className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border-2 border-biolumeTeal/50 bg-biolumeTeal/15 text-biolumeTeal text-sm font-semibold hover:bg-biolumeTeal/25 hover:shadow-[0_0_20px_rgba(0,255,229,0.15)] transition"
                >
                  <Download className="h-4 w-4" />
                  Download report (PDF)
                </button>
              </div>
            </div>
          </motion.section>

          {/* Charts grid */}
          <div className="relative z-10 grid grid-cols-1 lg:grid-cols-2 gap-5 sm:gap-6 max-w-5xl mx-auto w-full">
            <motion.section
              ref={chart1Ref}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className={CHART_CARD_CLASS}
              style={{ borderLeft: `4px solid ${CHART_TEAL}` }}
            >
              <h2 className="text-base font-semibold text-white/95 mb-0.5">Market share</h2>
              <p className="text-xs text-white/50 mb-4">Competitor share of addressable market</p>
              <div className="h-[280px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={marketShareData} margin={{ top: 12, right: 16, left: 8, bottom: 12 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" vertical={false} />
                    <XAxis dataKey="name" stroke="rgba(255,255,255,0.5)" fontSize={11} tickLine={false} axisLine={false} />
                    <YAxis stroke="rgba(255,255,255,0.5)" fontSize={11} tickLine={false} axisLine={false} />
                    <Tooltip
                      {...TOOLTIP_STYLE}
                      formatter={(value: number | undefined) => [value != null ? `${value}%` : "", "Share"]}
                    />
                    <Bar dataKey="share" name="Share" radius={[8, 8, 0, 0]} maxBarSize={44}>
                      {marketShareData.map((entry, i) => (
                        <Cell key={i} fill={entry.fill} stroke="rgba(0,0,0,0.15)" strokeWidth={1} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </motion.section>

            <motion.section
              ref={chart2Ref}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className={CHART_CARD_CLASS}
              style={{ borderLeft: `4px solid ${CHART_VIOLET}` }}
            >
              <h2 className="text-base font-semibold text-white/95 mb-0.5">Opportunity vs demand</h2>
              <p className="text-xs text-white/50 mb-4">By segment (0–100 index)</p>
              <div className="h-[280px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart
                    data={opportunityGapData}
                    margin={{ top: 12, right: 16, left: 8, bottom: 12 }}
                    layout="vertical"
                    barGap={8}
                  >
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" horizontal={false} />
                    <XAxis type="number" stroke="rgba(255,255,255,0.5)" fontSize={11} domain={[0, 100]} tickLine={false} axisLine={false} />
                    <YAxis type="category" dataKey="segment" stroke="rgba(255,255,255,0.5)" fontSize={11} width={110} tickLine={false} axisLine={false} />
                    <Tooltip {...TOOLTIP_STYLE} />
                    <Legend wrapperStyle={{ paddingTop: 8 }} formatter={(value) => <span className="text-white/80 text-xs">{value}</span>} />
                    <Bar dataKey="gap" name="Opportunity gap" fill={CHART_TEAL} radius={[0, 8, 8, 0]} maxBarSize={16} stroke="rgba(0,0,0,0.12)" strokeWidth={1} />
                    <Bar dataKey="demand" name="Demand index" fill={CHART_VIOLET} radius={[0, 8, 8, 0]} maxBarSize={16} stroke="rgba(0,0,0,0.12)" strokeWidth={1} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </motion.section>

            <motion.section
              ref={chart3Ref}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className={CHART_CARD_CLASS}
              style={{ borderLeft: `4px solid ${CHART_TEAL}` }}
            >
              <h2 className="text-base font-semibold text-white/95 mb-0.5">Market vs competitor trend</h2>
              <p className="text-xs text-white/50 mb-4">Monthly index (Jan–Jun)</p>
              <div className="h-[280px]">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={trendData} margin={{ top: 12, right: 16, left: 8, bottom: 12 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" />
                    <XAxis dataKey="month" stroke="rgba(255,255,255,0.5)" fontSize={11} tickLine={false} axisLine={false} />
                    <YAxis stroke="rgba(255,255,255,0.5)" fontSize={11} tickLine={false} axisLine={false} domain={[55, 90]} />
                    <Tooltip {...TOOLTIP_STYLE} />
                    <Legend wrapperStyle={{ paddingTop: 8 }} formatter={(value) => <span className="text-white/80 text-xs">{value}</span>} />
                    <Line type="monotone" dataKey="market" name="Market" stroke={CHART_TEAL} strokeWidth={2.5} dot={{ fill: CHART_TEAL, stroke: "rgba(0,0,0,0.2)", strokeWidth: 1, r: 4 }} activeDot={{ r: 5, fill: CHART_TEAL, stroke: "rgba(255,255,255,0.6)", strokeWidth: 2 }} />
                    <Line type="monotone" dataKey="competitors" name="Competitors" stroke={CHART_VIOLET} strokeWidth={2.5} dot={{ fill: CHART_VIOLET, stroke: "rgba(0,0,0,0.2)", strokeWidth: 1, r: 4 }} activeDot={{ r: 5, fill: CHART_VIOLET, stroke: "rgba(255,255,255,0.6)", strokeWidth: 2 }} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </motion.section>

            <motion.section
              ref={chart4Ref}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
              className={CHART_CARD_CLASS}
              style={{ borderLeft: `4px solid ${CHART_VIOLET}` }}
            >
              <h2 className="text-base font-semibold text-white/95 mb-0.5">Share breakdown</h2>
              <p className="text-xs text-white/50 mb-4">Distribution by competitor</p>
              <div className="h-[280px]">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={marketShareData}
                      dataKey="share"
                      nameKey="name"
                      cx="50%"
                      cy="50%"
                      innerRadius={56}
                      outerRadius={92}
                      paddingAngle={3}
                      stroke="rgba(15,23,42,0.5)"
                      strokeWidth={2}
                      label={(props) => {
                        const RADIAN = Math.PI / 180;
                        const cx = props.cx ?? 0;
                        const cy = props.cy ?? 0;
                        const midAngle = props.midAngle ?? 0;
                        const innerRadius = props.innerRadius ?? 0;
                        const outerRadius = props.outerRadius ?? 0;
                        const radius = innerRadius + (outerRadius - innerRadius) * 0.5;
                        const x = cx + radius * Math.cos(-midAngle * RADIAN);
                        const y = cy + radius * Math.sin(-midAngle * RADIAN);
                        const name = props.name ?? (props.payload as { name?: string } | undefined)?.name ?? "";
                        const pct =
                          props.percent != null
                            ? `${(props.percent * 100).toFixed(0)}%`
                            : `${(props.payload as { share?: number } | undefined)?.share ?? 0}%`;
                        return (
                          <text
                            x={x}
                            y={y}
                            fill="rgba(226, 232, 240, 0.95)"
                            fontSize={11}
                            fontWeight={500}
                            textAnchor="middle"
                            dominantBaseline="middle"
                          >
                            {name} {pct}
                          </text>
                        );
                      }}
                    >
                      {marketShareData.map((_, i) => (
                        <Cell key={i} fill={pieColors[i % pieColors.length]} stroke="rgba(0,0,0,0.15)" strokeWidth={1} />
                      ))}
                    </Pie>
                    <Tooltip {...TOOLTIP_STYLE} formatter={(value: number | undefined) => [value != null ? `${value}%` : "", "Share"]} />
                    <Legend wrapperStyle={{ paddingTop: 8 }} formatter={(value) => <span className="text-white/80 text-xs">{value}</span>} />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </motion.section>
          </div>
        </>
      )}
    </main>
  );
}
