"use client";

import { useState, useEffect, useRef, useCallback, useMemo } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowLeft, Cpu, X, Plus, Send, Download, Eye, Image as ImageIcon, Paperclip } from "lucide-react";
import JSZip from "jszip";
import { useSharedWorkspace } from "../../../src/context/SharedWorkspaceContext";

const BACKEND_BASE_URL = process.env.NEXT_PUBLIC_BACKEND_URL ?? "http://127.0.0.1:8000/api";

const SOFTWARE_KEYWORDS = /app|software|platform|saas|api|web\s*(app|site|page)?|dashboard|digital\s*(product|tool)|tech\s*(product|stack)|software\s*(product|company)/i;

function isSoftwareProject(marketGap: string | null | undefined): boolean {
  if (!marketGap || !marketGap.trim()) return false;
  return SOFTWARE_KEYWORDS.test(marketGap.trim());
}

const INITIAL_PLAN = [
  "Authentication using Supabase",
  "Vector DB for Trench Market Data",
  "REST API for depth sensor endpoints",
  "Next.js app shell with dashboard",
];

const MOCK_FILES = [
  "src/lib/auth.ts",
  "src/lib/vector-db.ts",
  "src/app/api/sensors/route.ts",
  "src/components/Dashboard.tsx",
  "package.json",
  "README.md",
];

const GENERATED_FILE_CONTENT: Record<string, string> = {
  "src/lib/auth.ts": `// Generated by Code Lab · Authentication (Supabase)
export async function getSession() {
  // TODO: integrate Supabase auth
  return null;
}
export async function signOut() {
  // TODO
}
`,
  "src/lib/vector-db.ts": `// Generated by Code Lab · Vector DB for Trench Market Data
export async function queryVectorDb(embedding: number[]) {
  // TODO: connect to vector store
  return [];
}
`,
  "src/app/api/sensors/route.ts": `// Generated by Code Lab · Depth sensor API
import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({ sensors: [] });
}
export async function POST(request: Request) {
  const body = await request.json();
  return NextResponse.json({ received: body });
}
`,
  "src/components/Dashboard.tsx": `// Generated by Code Lab · Dashboard shell
export default function Dashboard() {
  return (
    <div className="p-4">
      <h1>Dashboard</h1>
      <p>Generated scaffold — customize as needed.</p>
    </div>
  );
}
`,
  "package.json": `{
  "name": "code-lab-scaffold",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "latest",
    "react": "latest",
    "react-dom": "latest"
  }
}
`,
  "README.md": `# Code Lab Scaffold

Generated by Founder's Flight Deck · Code Lab.

## Setup

\`npm install\`
\`npm run dev\`

## Structure

- \`src/lib/auth.ts\` — Authentication
- \`src/lib/vector-db.ts\` — Vector DB for market data
- \`src/app/api/sensors/route.ts\` — Depth sensor API
- \`src/components/Dashboard.tsx\` — Dashboard UI
`,
};

export default function CodeLabPage() {
  const { sharedWorkspace } = useSharedWorkspace();
  const isSoftware = useMemo(
    () => isSoftwareProject(sharedWorkspace?.market_gap),
    [sharedWorkspace?.market_gap],
  );

  const [draftPlan, setDraftPlan] = useState<string[]>(INITIAL_PLAN);
  const [newItemInput, setNewItemInput] = useState("");
  const [userChatInput, setUserChatInput] = useState("");
  const [freeFormRequest, setFreeFormRequest] = useState("");
  const [isBuilding, setIsBuilding] = useState(false);
  const [buildComplete, setBuildComplete] = useState(false);
  const [weldingTrigger, setWeldingTrigger] = useState(false);
  const [isCallingBuild, setIsCallingBuild] = useState(false);
  const [buildError, setBuildError] = useState<string | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  const [previewError, setPreviewError] = useState<string | null>(null);
  const [editInput, setEditInput] = useState("");
  const [isSendingEdit, setIsSendingEdit] = useState(false);
  const [editError, setEditError] = useState<string | null>(null);
  const [editSuccess, setEditSuccess] = useState(false);
  const [chatTurns, setChatTurns] = useState<{ user: string; applied: boolean }[]>([]);
  const [generatedFilePaths, setGeneratedFilePaths] = useState<string[]>([]);
  const [technicalRiskScore] = useState(72);
  const [progressDone, setProgressDone] = useState<Set<number>>(new Set());
  const [terminalLines, setTerminalLines] = useState<string[]>([]);
  const terminalEndRef = useRef<HTMLDivElement>(null);
  const editFileInputRef = useRef<HTMLInputElement | null>(null);

  const terminalFiles = generatedFilePaths.length > 0 ? generatedFilePaths : MOCK_FILES;

  const architectMessage =
    "Technical Risk Score based on current plan. Add more specifics to lower risk.";

  const handleDownloadGeneratedCode = useCallback(async () => {
    try {
      const res = await fetch(`${BACKEND_BASE_URL}/agents/code-lab/artifact`);
      if (res.ok) {
        const blob = await res.blob();
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = "code-lab-scaffold.zip";
        a.click();
        URL.revokeObjectURL(url);
        return;
      }
    } catch {
      // fall through to mock zip
    }
    const zip = new JSZip();
    MOCK_FILES.forEach((path) => {
      const content = GENERATED_FILE_CONTENT[path] ?? `// Generated: ${path}\n`;
      zip.file(path, content);
    });
    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "code-lab-scaffold.zip";
    a.click();
    URL.revokeObjectURL(url);
  }, []);

  const handlePreview = useCallback(async () => {
    setPreviewError(null);
    try {
      const res = await fetch(`${BACKEND_BASE_URL}/agents/code-lab/preview`);
      if (!res.ok) {
        setPreviewError("No preview available. Build a project that includes an HTML file (e.g. index.html) first.");
        return;
      }
      setShowPreview(true);
    } catch {
      setPreviewError("Could not load preview. Is the backend running?");
    }
  }, []);

  const handleEditSubmit = useCallback(async () => {
    const msg = editInput.trim();
    if (!msg || isSendingEdit) return;
    setEditError(null);
    setEditSuccess(false);
    setIsSendingEdit(true);
    try {
      const res = await fetch(`${BACKEND_BASE_URL}/agents/code-lab/edit`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: msg,
          attachments: editAttachments,
        }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        setEditError((data as { detail?: string }).detail ?? "Edit failed");
        setChatTurns((prev) => [...prev.slice(-9), { user: msg, applied: false }]);
        return;
      }
      setEditInput("");
      setEditSuccess(true);
      setChatTurns((prev) => [...prev.slice(-9), { user: msg, applied: true }]);
      setTimeout(() => setEditSuccess(false), 3000);
    } catch (e) {
      setEditError(e instanceof Error ? e.message : "Network error");
      setChatTurns((prev) => [...prev.slice(-9), { user: msg, applied: false }]);
    } finally {
      setIsSendingEdit(false);
    }
  }, [editInput, isSendingEdit]);

  useEffect(() => {
    if (!isBuilding || buildComplete) return;
    const count = terminalFiles.length;
    const interval = setInterval(() => {
      const done = progressDone.size;
      if (done < count) {
        setProgressDone((prev) => new Set([...prev, done]));
      }
    }, 800);
    return () => clearInterval(interval);
  }, [isBuilding, buildComplete, terminalFiles.length, progressDone.size]);

  useEffect(() => {
    if (!isBuilding) return;
    const files = generatedFilePaths.length > 0 ? generatedFilePaths : MOCK_FILES;
    if (terminalLines.length >= files.length * 2 + 2) {
      setBuildComplete(true);
      return;
    }
    const t = setTimeout(() => {
      const i = terminalLines.length;
      if (i % 2 === 0) {
        const fileIdx = Math.floor(i / 2);
        setTerminalLines((prev) => [
          ...prev,
          `Generating ${files[fileIdx] ?? "..."}`,
        ]);
      } else {
        setTerminalLines((prev) => [...prev, "✓ Done"]);
      }
    }, 600);
    return () => clearTimeout(t);
  }, [isBuilding, terminalLines.length, generatedFilePaths]);

  useEffect(() => {
    terminalEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [terminalLines]);

  const handleCommenceConstruction = async () => {
    setBuildError(null);
    setIsCallingBuild(true);
    let ok = false;
    try {
      const res = await fetch(`${BACKEND_BASE_URL}/agents/code-lab/build`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ items: draftPlan, mode: "app" }),
      });
      const data = await res.json().catch(() => ({}));
      ok = res.ok;
      if (res.ok) {
        const paths = (data as { code_lab?: { generated_file_paths?: string[] } })?.code_lab?.generated_file_paths;
        if (Array.isArray(paths) && paths.length > 0) {
          setGeneratedFilePaths(paths);
        } else {
          try {
            const fr = await fetch(`${BACKEND_BASE_URL}/agents/code-lab/files`);
            const fd = await fr.json().catch(() => ({}));
            const list = (fd as { paths?: string[] })?.paths;
            if (Array.isArray(list) && list.length > 0) setGeneratedFilePaths(list);
            else setGeneratedFilePaths([]);
          } catch {
            setGeneratedFilePaths([]);
          }
        }
      } else {
        setGeneratedFilePaths([]);
        setBuildError((data as { detail?: string }).detail ?? "Build request failed");
      }
    } catch (e) {
      setBuildError(e instanceof Error ? e.message : "Network error");
      setGeneratedFilePaths([]);
    } finally {
      setIsCallingBuild(false);
    }
    if (!ok) return;
    setTerminalLines([]);
    setProgressDone(new Set());
    setBuildComplete(false);
    setWeldingTrigger(true);
    setTimeout(() => {
      setWeldingTrigger(false);
      setIsBuilding(true);
    }, 1200);
  };

  const addPlanItem = () => {
    const t = newItemInput.trim();
    if (t) {
      setDraftPlan((prev) => [...prev, t]);
      setNewItemInput("");
    }
  };

  const removePlanItem = (index: number) => {
    setDraftPlan((prev) => prev.filter((_, i) => i !== index));
  };

  const handleUserSubmit = () => {
    const t = userChatInput.trim();
    if (t) {
      setDraftPlan((prev) => [...prev, t]);
      setUserChatInput("");
    }
  };

  const handleFreeFormBuild = async () => {
    const t = freeFormRequest.trim();
    if (!t) return;
    setBuildError(null);
    setIsCallingBuild(true);
    let ok = false;
    try {
      const res = await fetch(`${BACKEND_BASE_URL}/agents/code-lab/build`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ items: [t], mode: "html" }),
      });
      const data = await res.json().catch(() => ({}));
      ok = res.ok;
      if (res.ok) {
        const paths = (data as { code_lab?: { generated_file_paths?: string[] } })?.code_lab?.generated_file_paths;
        if (Array.isArray(paths) && paths.length > 0) {
          setGeneratedFilePaths(paths);
        } else {
          try {
            const fr = await fetch(`${BACKEND_BASE_URL}/agents/code-lab/files`);
            const fd = await fr.json().catch(() => ({}));
            const list = (fd as { paths?: string[] })?.paths;
            if (Array.isArray(list) && list.length > 0) setGeneratedFilePaths(list);
            else setGeneratedFilePaths([]);
          } catch {
            setGeneratedFilePaths([]);
          }
        }
      } else {
        setGeneratedFilePaths([]);
        setBuildError((data as { detail?: string }).detail ?? "Build request failed");
      }
    } catch (e) {
      setBuildError(e instanceof Error ? e.message : "Network error");
      setGeneratedFilePaths([]);
    } finally {
      setIsCallingBuild(false);
    }
    if (!ok) return;
    setDraftPlan([t]);
    setFreeFormRequest("");
    setTerminalLines([]);
    setProgressDone(new Set());
    setBuildComplete(false);
    setWeldingTrigger(true);
    setTimeout(() => {
      setWeldingTrigger(false);
      setIsBuilding(true);
    }, 1200);
  };

  // New: quick "create page" helper that asks Nova only for a single file's content
  const [createPagePath, setCreatePagePath] = useState("src/app/contact/page.tsx");
  const [createPageDescription, setCreatePageDescription] = useState(
    "A simple contact page with a form (name, email, message) and a submit button.",
  );
  const [isCreatingPage, setIsCreatingPage] = useState(false);
  const [createPageError, setCreatePageError] = useState<string | null>(null);
  const [createPageSuccess, setCreatePageSuccess] = useState(false);

  const handleCreatePage = async () => {
    const path = createPagePath.trim();
    const desc = createPageDescription.trim();
    if (!path) {
      setCreatePageError("Path is required (e.g. src/app/contact/page.tsx).");
      return;
    }
    setCreatePageError(null);
    setCreatePageSuccess(false);
    setIsCreatingPage(true);
    try {
      const res = await fetch(`${BACKEND_BASE_URL}/agents/code-lab/create-page`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ path, description: desc }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        setCreatePageError((data as { detail?: string }).detail ?? "Page generation failed.");
        return;
      }
      const paths = (data as { code_lab?: { generated_file_paths?: string[] } })?.code_lab?.generated_file_paths;
      if (Array.isArray(paths) && paths.length > 0) {
        setGeneratedFilePaths(paths);
      } else {
        try {
          const fr = await fetch(`${BACKEND_BASE_URL}/agents/code-lab/files`);
          const fd = await fr.json().catch(() => ({}));
          const list = (fd as { paths?: string[] })?.paths;
          if (Array.isArray(list) && list.length > 0) setGeneratedFilePaths(list);
          else setGeneratedFilePaths([]);
        } catch {
          setGeneratedFilePaths([]);
        }
      }
      setCreatePageSuccess(true);
      setTimeout(() => setCreatePageSuccess(false), 3000);
    } catch (e) {
      setCreatePageError(e instanceof Error ? e.message : "Network error.");
    } finally {
      setIsCreatingPage(false);
    }
  };

  // Nova Canvas mock images for Code Lab
  const [imagePrompt, setImagePrompt] = useState("");
  const [imageColor, setImageColor] = useState<string>("");
  const [isGeneratingImage, setIsGeneratingImage] = useState(false);
  const [generatedImages, setGeneratedImages] = useState<{ path: string; filename: string }[]>([]);
  const [imageError, setImageError] = useState<string | null>(null);

  // Attach existing images (user uploads) to edits
  const [editAttachments, setEditAttachments] = useState<{ filename: string; path: string }[]>([]);
  const [showGenerateImageMode, setShowGenerateImageMode] = useState(false);

  const handleGenerateImage = async () => {
    const prompt = imagePrompt.trim();
    if (!prompt) {
      setImageError("Describe what you want in the image.");
      return;
    }
    setImageError(null);
    setIsGeneratingImage(true);
    try {
      const res = await fetch(`${BACKEND_BASE_URL}/agents/code-lab/generate-image`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt, color_hex: imageColor || null }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        setImageError((data as { detail?: string }).detail ?? "Image generation failed.");
        return;
      }
      const img = data as { path: string; filename: string };
      setGeneratedImages((prev) => [...prev, img]);
      setImagePrompt("");
    } catch (e) {
      setImageError(e instanceof Error ? e.message : "Network error.");
    } finally {
      setIsGeneratingImage(false);
    }
  };

  const handleEditFileUpload = async (files: FileList | null) => {
    if (!files || files.length === 0) return;
    try {
      const form = new FormData();
      Array.from(files).forEach((f) => form.append("files", f));
      const res = await fetch(`${BACKEND_BASE_URL}/agents/code-lab/upload`, {
        method: "POST",
        body: form,
      });
      if (!res.ok) return;
      const data = (await res.json()) as { uploads?: { filename: string; path: string }[] };
      if (Array.isArray(data.uploads) && data.uploads.length > 0) {
        setEditAttachments((prev) => [...prev, ...data.uploads!]);
      }
    } catch {
      // ignore upload errors for now
    } finally {
      if (editFileInputRef.current) {
        editFileInputRef.current.value = "";
      }
    }
  };

  return (
    <main className="relative min-h-screen flex flex-col bg-[#050b14] overflow-hidden">
      {/* Background: fishswim video + gradient overlay */}
      <div className="fixed inset-0 z-0">
        <video
          autoPlay
          muted
          loop
          playsInline
          className="absolute inset-0 w-full h-full object-cover"
          aria-hidden
        >
          <source src="/videos/fishswim.mp4" type="video/mp4" />
        </video>
        <div
          className="absolute inset-0 bg-gradient-to-b from-black/60 via-[#0a1628]/85 to-black/80"
          aria-hidden
        />
      </div>

      {/* Header */}
      <header className="relative z-10 flex items-center gap-4 px-4 py-3 border-b border-white/10 bg-black/30 backdrop-blur-xl">
        <Link
          href="/mission-control"
          className="flex items-center gap-2 text-sm text-white/80 hover:text-biolumeTeal transition"
        >
          <ArrowLeft className="h-4 w-4" />
          Mission Control
        </Link>
        <span className="text-white/40">›</span>
        <span className="text-sm font-medium text-white">Code Lab</span>
        <span className="text-xs text-white/50 ml-2">AI Architect · Plan & Build</span>
      </header>

      {/* Main content */}
      <div className="relative z-10 flex-1 flex flex-col min-h-0 p-4 lg:p-6">
        <AnimatePresence mode="wait">
          {!isBuilding ? (
            isSoftware ? (
            /* Stage 1a: Software project — Technical scaffold (edit plan, then build) */
            <motion.div
              key="blueprint"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex-1 flex flex-col gap-4 max-w-4xl mx-auto w-full"
            >
              {/* Architect feedback: avatar + risk score */}
              <div className="flex items-center gap-3 flex-shrink-0">
                <div className="w-10 h-10 rounded-xl bg-biolumeTeal/20 border border-biolumeTeal/40 flex items-center justify-center">
                  <Cpu className="w-5 h-5 text-biolumeTeal" />
                </div>
                <div>
                  <p className="text-xs font-medium text-white">Nova 2 Pro · Technical Risk Score</p>
                  <p className="text-lg font-bold text-biolumeTeal">{technicalRiskScore}%</p>
                  <p className="text-[0.65rem] text-white/50 max-w-md">{architectMessage}</p>
                </div>
              </div>

              {/* Plan Panel: editable glass card */}
              <motion.div
                className={`rounded-2xl border-2 overflow-hidden backdrop-blur-xl flex flex-col min-h-[280px] ${
                  weldingTrigger ? "welding-spark-once" : ""
                }`}
                style={{
                  background: "rgba(5, 11, 20, 0.6)",
                  borderColor: weldingTrigger ? "rgba(0,255,229,0.7)" : "rgba(255,255,255,0.15)",
                  boxShadow: weldingTrigger
                    ? "0 0 30px rgba(0,255,229,0.4), inset 0 0 30px rgba(0,255,229,0.08)"
                    : "0 25px 50px -12px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.05)",
                }}
              >
                <div className="p-4 border-b border-white/10">
                  <h2 className="text-sm font-semibold text-white">Technical scaffold</h2>
                  <p className="text-xs text-white/50 mt-0.5">Edit the plan below, then commence construction.</p>
                </div>
                <ul className="flex-1 p-4 space-y-2 overflow-y-auto">
                  {draftPlan.map((item, index) => (
                    <li
                      key={`${index}-${item}`}
                      className="flex items-center gap-2 group text-sm text-white/90"
                    >
                      <span className="flex-1 py-1">{item}</span>
                      <button
                        type="button"
                        onClick={() => removePlanItem(index)}
                        className="p-1 rounded text-white/50 hover:text-red-400 hover:bg-white/10 opacity-0 group-hover:opacity-100 transition"
                        aria-label="Remove"
                      >
                        <X className="w-4 h-4" />
                      </button>
                    </li>
                  ))}
                </ul>
                <div className="p-4 border-t border-white/10 flex gap-2">
                  <input
                    type="text"
                    value={newItemInput}
                    onChange={(e) => setNewItemInput(e.target.value)}
                    onKeyDown={(e) => e.key === "Enter" && addPlanItem()}
                    placeholder="Add requirement (e.g. Add API endpoint for depth sensors)"
                    className="flex-1 px-3 py-2 rounded-lg bg-white/5 border border-white/15 text-white text-sm placeholder:text-white/40 focus:outline-none focus:border-biolumeTeal/50"
                  />
                  <button
                    type="button"
                    onClick={addPlanItem}
                    className="px-3 py-2 rounded-lg bg-biolumeTeal/20 border border-biolumeTeal/40 text-biolumeTeal hover:bg-biolumeTeal/30 transition flex items-center gap-1"
                  >
                    <Plus className="w-4 h-4" />
                    Add
                  </button>
                </div>
              </motion.div>

              {/* Quick create page / route helper */}
              <div className="rounded-2xl border border-white/15 bg-black/45 backdrop-blur-xl p-4 space-y-2">
                <div className="flex items-center justify-between gap-2">
                  <div>
                    <h3 className="text-xs font-semibold text-white/80 uppercase tracking-[0.16em]">
                      Quick create page
                    </h3>
                    <p className="text-[0.7rem] text-white/55 mt-0.5">
                      Ask Code Lab to generate a single file (like a contact page) and add it to the scaffold.
                    </p>
                  </div>
                </div>
                <div className="flex flex-col md:flex-row gap-2 mt-1">
                  <input
                    type="text"
                    value={createPagePath}
                    onChange={(e) => setCreatePagePath(e.target.value)}
                    className="flex-1 px-3 py-2 rounded-lg bg-white/5 border border-white/15 text-white text-xs md:text-sm placeholder:text-white/40 focus:outline-none focus:border-biolumeTeal/50"
                    placeholder="src/app/contact/page.tsx"
                  />
                  <button
                    type="button"
                    onClick={() => void handleCreatePage()}
                    disabled={isCreatingPage}
                    className="px-3 py-2 rounded-lg bg-biolumeTeal/20 border border-biolumeTeal/40 text-biolumeTeal hover:bg-biolumeTeal/30 transition text-xs md:text-sm flex items-center gap-1"
                  >
                    <Plus className="w-4 h-4" />
                    {isCreatingPage ? "Creating…" : "Create page"}
                  </button>
                </div>
                <textarea
                  value={createPageDescription}
                  onChange={(e) => setCreatePageDescription(e.target.value)}
                  rows={2}
                  className="mt-2 w-full px-3 py-2 rounded-lg bg-white/5 border border-white/15 text-[0.75rem] text-white placeholder:text-white/40 focus:outline-none focus:border-biolumeTeal/50"
                  placeholder="Describe what this page should do and look like…"
                />
                {createPageError && (
                  <p className="text-[0.7rem] text-amber-300 mt-1">{createPageError}</p>
                )}
                {createPageSuccess && !createPageError && (
                  <p className="text-[0.7rem] text-biolumeTeal mt-1">
                    Page created and added to the scaffold. Re-download or preview to use it.
                  </p>
                )}
              </div>

              {/* Command line input: [User]: ... */}
              <div className="rounded-xl border border-white/15 bg-black/40 backdrop-blur-xl p-3 flex gap-2">
                <span className="text-biolumeTeal text-sm font-mono shrink-0">[User]:</span>
                <input
                  type="text"
                  value={userChatInput}
                  onChange={(e) => setUserChatInput(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleUserSubmit()}
                  placeholder="Update plan to include..."
                  className="flex-1 bg-transparent text-white text-sm placeholder:text-white/40 focus:outline-none font-mono"
                />
                <button
                  type="button"
                  onClick={handleUserSubmit}
                  className="p-2 rounded-lg bg-biolumeTeal/20 text-biolumeTeal hover:bg-biolumeTeal/30 transition"
                >
                  <Send className="w-4 h-4" />
                </button>
              </div>

              {/* COMMENCE CONSTRUCTION button */}
              {buildError && (
                <p className="text-sm text-red-400 text-center">{buildError}</p>
              )}
              <motion.button
                type="button"
                onClick={() => void handleCommenceConstruction()}
                disabled={isCallingBuild}
                className="mt-auto py-4 px-6 rounded-xl border-2 border-biolumeTeal bg-biolumeTeal/10 text-biolumeTeal font-bold text-sm uppercase tracking-wider flex items-center justify-center gap-2 self-center min-w-[280px] shadow-[0_0_30px_rgba(0,255,229,0.2)] disabled:opacity-50 disabled:cursor-not-allowed"
                animate={{
                  boxShadow: [
                    "0 0 20px rgba(0,255,229,0.25), 0 0 40px rgba(0,255,229,0.1)",
                    "0 0 35px rgba(0,255,229,0.5), 0 0 60px rgba(0,255,229,0.2)",
                    "0 0 20px rgba(0,255,229,0.25), 0 0 40px rgba(0,255,229,0.1)",
                  ],
                }}
                transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
              >
                <Cpu className="w-5 h-5" />
                {isCallingBuild ? "Generating code…" : "Commence construction"}
              </motion.button>
            </motion.div>
            ) : (
            /* Stage 1b: Non-software — free-form "build anything" box */
            <motion.div
              key="freeform"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex-1 flex flex-col gap-4 max-w-2xl mx-auto w-full"
            >
              <div className="flex items-center gap-3 flex-shrink-0">
                <div className="w-10 h-10 rounded-xl bg-biolumeTeal/20 border border-biolumeTeal/40 flex items-center justify-center">
                  <Cpu className="w-5 h-5 text-biolumeTeal" />
                </div>
                <div>
                  <p className="text-xs font-medium text-white">Code Lab</p>
                  <p className="text-[0.65rem] text-white/50 max-w-md">
                    Describe what you want to build. Anything—e.g. a webpage for your startup, a landing page, an order form.
                  </p>
                </div>
              </div>
              <div
                className="rounded-2xl border-2 overflow-hidden backdrop-blur-xl flex flex-col min-h-[200px]"
                style={{
                  background: "rgba(5, 11, 20, 0.6)",
                  borderColor: "rgba(255,255,255,0.15)",
                  boxShadow: "0 25px 50px -12px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.05)",
                }}
              >
                <div className="p-4 border-b border-white/10">
                  <h2 className="text-sm font-semibold text-white">What do you want to build?</h2>
                  <p className="text-xs text-white/50 mt-0.5">Type anything. We&apos;ll help you build it.</p>
                </div>
                <div className="flex-1 p-4">
                  <textarea
                    value={freeFormRequest}
                    onChange={(e) => setFreeFormRequest(e.target.value)}
                    placeholder="e.g. Create a simple landing page for my pen startup with a hero, feature grid, and pricing section"
                    rows={4}
                    className="w-full px-3 py-3 rounded-lg bg-white/5 border border-white/15 text-white text-sm placeholder:text-white/40 focus:outline-none focus:border-biolumeTeal/50 resize-y min-h-[120px]"
                  />
                </div>
                <div className="p-4 border-t border-white/10 space-y-2">
                  {buildError && (
                    <p className="text-sm text-red-400 text-center">{buildError}</p>
                  )}
                  <button
                    type="button"
                    onClick={() => void handleFreeFormBuild()}
                    disabled={!freeFormRequest.trim() || isCallingBuild}
                    className="w-full py-3 px-6 rounded-xl border-2 border-biolumeTeal bg-biolumeTeal/20 text-biolumeTeal font-bold text-sm uppercase tracking-wider flex items-center justify-center gap-2 disabled:opacity-40 disabled:cursor-not-allowed hover:bg-biolumeTeal/30 transition"
                  >
                    <Cpu className="w-5 h-5" />
                    {isCallingBuild ? "Generating code…" : "Build it"}
                  </button>
                </div>
              </div>
            </motion.div>
            )
          ) : (
            /* Stage 2: Construction Phase */
            <motion.div
              key="construction"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex-1 flex flex-col gap-4 max-w-4xl mx-auto w-full"
            >
              {/* Minimized progress checklist */}
              <div className="rounded-xl border border-white/15 bg-black/40 backdrop-blur-xl p-4">
                <h3 className="text-xs font-semibold text-white/80 mb-3 uppercase tracking-wider">
                  Build progress
                </h3>
                <ul className="flex flex-wrap gap-2">
                  {terminalFiles.map((item, index) => (
                    <li
                      key={index}
                      className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-white/5 text-xs text-white/80"
                    >
                      {progressDone.has(index) ? (
                        <span className="text-biolumeTeal">✓</span>
                      ) : (
                        <span className="w-3 h-3 rounded-full border border-biolumeTeal/50 animate-pulse" />
                      )}
                      <span className="truncate max-w-[180px]">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Wireframe + Live terminal */}
              <div className="flex-1 rounded-2xl border-2 border-biolumeTeal/30 overflow-hidden bg-[#0a1118] shadow-[0_0_40px_rgba(0,255,229,0.15)] min-h-[260px] flex flex-col relative">
                {/* 3D wireframe "printing" background */}
                <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-30">
                  <svg className="absolute inset-0 w-full h-full" viewBox="0 0 400 200" preserveAspectRatio="xMidYMid slice">
                    <defs>
                      <linearGradient id="wireframe-teal" x1="0%" y1="0%" x2="100%" y2="100%">
                        <stop offset="0%" stopColor="rgba(0,255,229,0.6)" />
                        <stop offset="100%" stopColor="rgba(0,255,229,0.1)" />
                      </linearGradient>
                    </defs>
                    {/* Grid lines with stroke-dasharray "draw" animation */}
                    {[0, 50, 100, 150, 200, 250, 300, 350, 400].map((x, i) => (
                      <line
                        key={`v-${i}`}
                        x1={x}
                        y1={0}
                        x2={x}
                        y2={200}
                        stroke="url(#wireframe-teal)"
                        strokeWidth="0.5"
                        strokeDasharray="200"
                        strokeDashoffset="200"
                        style={{
                          animation: `wireframe-draw 2s ease-out ${i * 0.08}s forwards`,
                        }}
                      />
                    ))}
                    {[0, 40, 80, 120, 160, 200].map((y, i) => (
                      <line
                        key={`h-${i}`}
                        x1={0}
                        y1={y}
                        x2={400}
                        y2={y}
                        stroke="url(#wireframe-teal)"
                        strokeWidth="0.5"
                        strokeDasharray="400"
                        strokeDashoffset="400"
                        style={{
                          animation: `wireframe-draw 2.5s ease-out ${i * 0.1}s forwards`,
                        }}
                      />
                    ))}
                  </svg>
                </div>
                <div className="p-2 border-b border-white/10 flex items-center gap-2 relative z-10">
                  <span className="w-2 h-2 rounded-full bg-red-500/80" />
                  <span className="w-2 h-2 rounded-full bg-amber-500/80" />
                  <span className="w-2 h-2 rounded-full bg-green-500/80" />
                  <span className="text-xs text-white/50 ml-2 font-mono">Live code terminal</span>
                </div>
                <div className="flex-1 p-4 font-mono text-xs text-white/80 overflow-y-auto relative z-10">
                  {terminalLines.map((line, i) => (
                    <div key={i} className="leading-relaxed">
                      {line.startsWith("✓") ? (
                        <span className="text-biolumeTeal">{line}</span>
                      ) : (
                        <span className="text-white/90">{line}</span>
                      )}
                    </div>
                  ))}
                  {!buildComplete && (
                    <span className="inline-block w-2 h-4 bg-biolumeTeal/80 animate-pulse ml-0.5" />
                  )}
                  <div ref={terminalEndRef} />
                </div>
              </div>

              {buildComplete && (
                <>
                  <motion.div
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="flex justify-center gap-3 pb-4 flex-wrap"
                  >
                    <button
                      type="button"
                      onClick={handlePreview}
                      className="flex items-center gap-2 px-5 py-3 rounded-xl bg-white/10 border border-white/30 text-white font-medium text-sm hover:bg-white/20 transition"
                    >
                      <Eye className="w-4 h-4" />
                      Preview webpage
                    </button>
                    <button
                      type="button"
                      onClick={handleDownloadGeneratedCode}
                      className="flex items-center gap-2 px-5 py-3 rounded-xl bg-biolumeTeal/20 border border-biolumeTeal/50 text-biolumeTeal font-medium text-sm hover:bg-biolumeTeal/30 transition shadow-[0_0_20px_rgba(0,255,229,0.15)]"
                    >
                      <Download className="w-4 h-4" />
                      Download generated code
                    </button>
                    <button
                      type="button"
                      onClick={() => void handleCommenceConstruction()}
                      disabled={isCallingBuild}
                      className="flex items-center gap-2 px-5 py-3 rounded-xl bg-black/40 border border-white/25 text-white/80 text-sm hover:bg-black/60 transition disabled:opacity-40 disabled:cursor-not-allowed"
                    >
                      Regenerate
                    </button>
                  </motion.div>

                  {/* Edit / chat — Cursor-style */}
                  <motion.div
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.1 }}
                    className="rounded-xl border border-white/15 bg-black/40 backdrop-blur-xl overflow-hidden"
                  >
                    <div className="p-3 border-b border-white/10">
                      <h3 className="text-xs font-semibold text-white/90 uppercase tracking-wider">
                        Edit what you built
                      </h3>
                      <p className="text-[0.65rem] text-white/50 mt-0.5">
                        Ask for changes (e.g. &quot;Add a pricing section&quot;, &quot;Make the header sticky&quot;, &quot;Change colors to blue&quot;)
                      </p>
                    </div>
                    {chatTurns.length > 0 && (
                      <div className="p-3 border-b border-white/10 max-h-24 overflow-y-auto space-y-2">
                        {chatTurns.slice(-5).map((t, i) => (
                          <div key={i} className="flex items-start gap-2 text-xs">
                            <span className="text-biolumeTeal shrink-0">You:</span>
                            <span className="text-white/80 truncate flex-1">{t.user}</span>
                            {t.applied ? (
                              <span className="text-emerald-400 shrink-0">Applied</span>
                            ) : (
                              <span className="text-red-400 shrink-0">Failed</span>
                            )}
                          </div>
                        ))}
                      </div>
                    )}
                    {editAttachments.length > 0 && (
                      <div className="px-3 pt-2 pb-1 flex flex-wrap gap-2 border-b border-white/10">
                        {editAttachments.map((att, idx) => (
                          <span
                            key={`${att.path}-${idx}`}
                            className="inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-white/5 px-2 py-0.5 text-[0.65rem] text-white/80"
                          >
                            <Paperclip className="w-3 h-3" />
                            <span className="max-w-[140px] truncate" title={att.filename}>
                              {att.filename}
                            </span>
                            <button
                              type="button"
                              onClick={() =>
                                setEditAttachments((prev) => prev.filter((_, i) => i !== idx))
                              }
                              className="p-0.5 rounded hover:bg-white/15 text-white/70"
                              aria-label="Remove attachment"
                            >
                              <X className="w-3 h-3" />
                            </button>
                          </span>
                        ))}
                      </div>
                    )}
                    <div className="p-3 flex flex-col gap-2">
                      <div className="flex gap-2">
                      <textarea
                        value={editInput}
                        onChange={(e) => setEditInput(e.target.value)}
                        onKeyDown={(e) => {
                          if (e.key === "Enter" && !e.shiftKey) {
                            e.preventDefault();
                            void handleEditSubmit();
                          }
                        }}
                        placeholder="e.g. Make the hero headline shorter and bolder, or change the CTA button color to teal"
                        rows={2}
                        className="flex-1 px-3 py-2 rounded-lg bg-white/5 border border-white/15 text-white text-sm placeholder:text-white/40 focus:outline-none focus:border-biolumeTeal/50 resize-y min-h-[60px]"
                        disabled={isSendingEdit}
                      />
                      <button
                        type="button"
                        onClick={() => void handleEditSubmit()}
                        disabled={!editInput.trim() || isSendingEdit}
                        className="self-end px-4 py-2 rounded-lg bg-biolumeTeal/20 border border-biolumeTeal/40 text-biolumeTeal font-medium text-sm hover:bg-biolumeTeal/30 disabled:opacity-40 disabled:cursor-not-allowed transition flex items-center gap-1.5"
                      >
                        <Send className="w-4 h-4" />
                        {isSendingEdit ? "Applying…" : "Apply edit"}
                      </button>
                      </div>
                      <div className="flex justify-between items-center gap-2">
                        <label className="inline-flex items-center gap-1.5 text-[0.7rem] text-white/70 cursor-pointer">
                          <input
                            type="file"
                            ref={editFileInputRef}
                            className="hidden"
                            accept="image/*"
                            multiple
                            onChange={(e) => void handleEditFileUpload(e.target.files)}
                          />
                          <span className="inline-flex items-center gap-1 px-2 py-1 rounded-md border border-white/20 bg-white/5 hover:bg-white/10">
                            <Paperclip className="w-3.5 h-3.5" />
                            Attach images
                          </span>
                        </label>
                        <span className="text-[0.65rem] text-white/40">
                          Attached images will be available for this edit.
                        </span>
                      </div>
                    </div>
                    {editSuccess && (
                      <p className="px-3 pb-2 text-xs text-emerald-400">Updated. Preview or Download again to see changes.</p>
                    )}
                    {editError && (
                      <p className="px-3 pb-2 text-xs text-red-400">{editError}</p>
                    )}
                  </motion.div>

                  {/* Generate mock images (Nova Canvas) – toggle inside Edit what you built */}
                  <div className="mt-2 border-t border-white/10 pt-2 px-3 pb-3 flex flex-col gap-2">
                    <div className="flex items-center justify-between gap-2">
                      <p className="text-[0.65rem] text-white/45">
                        Enhance this page with AI‑generated illustrations.
                      </p>
                      <button
                        type="button"
                        onClick={() => setShowGenerateImageMode((v) => !v)}
                        className="inline-flex items-center gap-1.5 rounded-full border border-biolumeTeal/40 bg-biolumeTeal/10 px-3 py-1 text-[0.7rem] text-biolumeTeal hover:bg-biolumeTeal/20 hover:text-white transition"
                      >
                        <ImageIcon className="w-3.5 h-3.5" />
                        {showGenerateImageMode ? "Hide AI images" : "Generate image with AI"}
                      </button>
                    </div>
                    {showGenerateImageMode && (
                      <div className="mt-2 rounded-xl border border-white/15 bg-black/50 p-3 space-y-2">
                        <p className="text-[0.7rem] text-white/55">
                          Describe an illustration and we&apos;ll generate an image you can use in this project.
                        </p>
                        <div className="flex flex-col md:flex-row gap-2">
                          <input
                            type="text"
                            value={imagePrompt}
                            onChange={(e) => setImagePrompt(e.target.value)}
                            className="flex-1 px-3 py-2 rounded-lg bg-white/5 border border-white/15 text-white text-xs md:text-sm placeholder:text-white/40 focus:outline-none focus:border-biolumeTeal/50"
                            placeholder="e.g. Minimal line-art handbag icon on dark background"
                          />
                          <select
                            value={imageColor}
                            onChange={(e) => setImageColor(e.target.value)}
                            className="px-2 py-2 rounded-lg bg-white/5 border border-white/15 text-white text-xs md:text-sm focus:outline-none focus:border-biolumeTeal/50"
                          >
                            <option value="">Any color</option>
                            <option value="#FFFFFF">Mostly white</option>
                            <option value="#0EA5E9">Blue</option>
                            <option value="#22C55E">Green</option>
                          </select>
                          <button
                            type="button"
                            onClick={() => void handleGenerateImage()}
                            disabled={isGeneratingImage}
                            className="px-3 py-2 rounded-lg bg-biolumeTeal/20 border border-biolumeTeal/40 text-biolumeTeal hover:bg-biolumeTeal/30 transition text-xs md:text-sm flex items-center gap-1"
                          >
                            {isGeneratingImage ? "Generating…" : "Generate image"}
                          </button>
                        </div>
                        {imageError && <p className="text-[0.7rem] text-amber-300 mt-1">{imageError}</p>}
                        {generatedImages.length > 0 && (
                          <div className="mt-2 grid grid-cols-2 md:grid-cols-3 gap-2">
                            {generatedImages.map((img, idx) => {
                              const imagePath = `/agents/code-lab/image/${img.path}`;
                              const fullUrl = `${BACKEND_BASE_URL}${imagePath}`;
                              return (
                                <div
                                  key={`${img.path}-${idx}`}
                                  className="rounded-lg border border-white/15 bg-black/40 p-2 flex flex-col gap-1"
                                >
                                  <div className="w-full aspect-video rounded-md overflow-hidden bg-white/5 flex items-center justify-center">
                                    <img
                                      src={fullUrl}
                                      alt={img.filename}
                                      className="w-full h-full object-contain"
                                    />
                                  </div>
                                  <div className="flex items-center justify-between gap-2 mt-1">
                                    <p className="text-[0.6rem] text-white/60 break-all flex-1">
                                      {imagePath}
                                    </p>
                                    <a
                                      href={fullUrl}
                                      download={img.filename}
                                      className="p-1.5 rounded-md border border-white/20 bg-white/5 text-white/80 hover:bg-white/15 hover:text-white transition flex items-center justify-center"
                                      title="Download image"
                                    >
                                      <Download className="w-3.5 h-3.5" />
                                    </a>
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                </>
              )}
              {previewError && (
                <p className="text-xs text-red-300 text-center pb-2 max-w-xl mx-auto">
                  {previewError} Download the project and run it locally to preview full Next.js apps. In‑app preview only works when the build includes an HTML file (e.g. <code>index.html</code>).
                </p>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Preview modal */}
      <AnimatePresence>
        {showPreview && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex flex-col bg-black/90 backdrop-blur-sm"
          >
            <div className="flex items-center justify-between px-4 py-2 border-b border-white/10 bg-black/50">
              <span className="text-sm font-medium text-white">Preview — generated webpage</span>
              <button
                type="button"
                onClick={() => setShowPreview(false)}
                className="p-2 rounded-lg text-white/80 hover:text-white hover:bg-white/10 transition"
                aria-label="Close preview"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            <iframe
              title="Preview of generated webpage"
              src={`${BACKEND_BASE_URL}/agents/code-lab/preview`}
              className="flex-1 w-full min-h-0 border-0 bg-white"
            />
          </motion.div>
        )}
      </AnimatePresence>
    </main>
  );
}
